spring.application.name=recipe-recommender-xml-java

app.xml.recipes.path=src/main/resources/xml/recipes.xml
app.xml.users.path=src/main/resources/xml/users.xml
app.xml.recipes.schema=src/main/resources/xml/recipes.xsd
app.xml.users.schema=src/main/resources/xml/users.xsd

app.scraper.enabled=false

